-- Create departments table
create table departments (
  name text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create agents table
create table agents (
  name text primary key,
  department_name text references departments(name),
  email text,
  extension text,
  completed_orders integer default 0,
  total_orders integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create orders table
create table orders (
  id text primary key,
  title text not null,
  type text not null,
  status text not null,
  priority text not null,
  details jsonb,
  tasks jsonb,
  assigned_to text references agents(name),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  completed_at timestamp with time zone
);

-- Create activity_log table
create table activity_log (
  id bigint generated by default as identity primary key,
  action text not null,
  details jsonb,
  agent_name text references agents(name),
  order_id text references orders(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create order_categories table
create table order_categories (
  name text primary key,
  tasks text[] not null default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create RLS policies
alter table departments enable row level security;
alter table agents enable row level security;
alter table orders enable row level security;
alter table activity_log enable row level security;
alter table order_categories enable row level security;

-- Create policies for anonymous access (since we're using anon key)
create policy "Allow anonymous read access" on departments for select using (true);
create policy "Allow anonymous write access" on departments for insert with check (true);
create policy "Allow anonymous update access" on departments for update using (true);
create policy "Allow anonymous delete access" on departments for delete using (true);

create policy "Allow anonymous read access" on agents for select using (true);
create policy "Allow anonymous write access" on agents for insert with check (true);
create policy "Allow anonymous update access" on agents for update using (true);
create policy "Allow anonymous delete access" on agents for delete using (true);

create policy "Allow anonymous read access" on orders for select using (true);
create policy "Allow anonymous write access" on orders for insert with check (true);
create policy "Allow anonymous update access" on orders for update using (true);
create policy "Allow anonymous delete access" on orders for delete using (true);

create policy "Allow anonymous read access" on activity_log for select using (true);
create policy "Allow anonymous write access" on activity_log for insert with check (true);

create policy "Allow anonymous read access" on order_categories for select using (true);
create policy "Allow anonymous write access" on order_categories for insert with check (true);
create policy "Allow anonymous update access" on order_categories for update using (true);
create policy "Allow anonymous delete access" on order_categories for delete using (true);

-- Insert initial data
insert into departments (name) values ('Management'), ('Support'), ('Sales');

insert into order_categories (name, tasks) values 
  ('SIP Trunk', ARRAY[
    'CSA Signed',
    'Customer Created',
    'Account Created',
    'DID Provisioned',
    'Subscriptions Added',
    'Discounts Added',
    'Welcome Email Sent',
    'One time charges Invoiced',
    'Project Completed'
  ]),
  ('RO Cloud CPS', ARRAY[
    'CSA Signed',
    'Customer Created',
    'Accounts Created',
    'Inbound Routing Set',
    'Auto Attendant Set',
    'Phones Provisioned',
    'DID Provisioned',
    'Subscriptions Added',
    'Discounts Added',
    'Welcome Email Sent',
    'One time charges Invoiced',
    'Project Completed'
  ]),
  ('3CX Cloud/On Prem', ARRAY[
    'CSA Signed',
    'Customer Created',
    'Account Created',
    'DID Provisioned',
    '3CX Health & Performance Monitoring',
    '3CX License + Hosting',
    'Remote Phone System Configuration',
    'Subscriptions Added',
    'Discounts Added',
    'Welcome Email Sent',
    'One time charges Invoiced',
    'Project Completed'
  ]),
  ('One Time Order', ARRAY[
    'Ticket Created',
    'Customer Added in QB',
    'Invoice sent',
    'Payment Received',
    'Project Completed'
  ]);